eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 10 #服务刷新时间配置，每隔这个时间会主动心跳一次
  client:
    register-with-eureka: false # 注册到Eureka Server，默认true
    fetch-registry: false # 从Eureka Server获取注册信息，默认true

spring:
  profiles:
    include: redis-dev,rabbitmq-dev
  datasource:
    base:
      master:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/template?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&tinyInt1isBit=false
        username: root
        password: 12345678
      slave1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/template_slave1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&tinyInt1isBit=false
        username: root
        password: 12345678
      slave2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/template_slave2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&tinyInt1isBit=false
        username: root
        password: 12345678

canal:
  mode: close # simple,cluster,zookeeper,kafka,rocketMQ，默认：simple 可以使用一个不存在的选项关闭canal
  server: 127.0.0.1:11111 # canal的地址
  destination: example # 数据同步的目的地，默认：example
  
template:
  domain: http://d-domain.com
  enable:
    redis: false
    redisson: false
    idempotent: false
    rabbitmq: false
    elasticsearch: false
    data-encypt: false
    access-control: false
  mock:
    time: false
