lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - "java.lang:type=OperatingSystem"
  - "java.lang:type=MemoryPool,name=PS Eden Space"
  - "java.lang:type=MemoryPool,name=PS Survivor Space"
  - "java.lang:type=MemoryPool,name=PS Old Gen"
  - "java.lang:type=MemoryPool,name=Metaspace"
  - "java.lang:type=GarbageCollector,name=PS Scavenge"
  - "java.lang:type=GarbageCollector,name=PS MarkSweep"
  - "java.lang:type=Memory"
rules:
  - pattern: 'java.lang<type=OperatingSystem><>(committed_virtual_memory|free_physical_memory|free_swap_space|total_physical_memory|total_swap_space)_size:'
    name: os_$1_bytes
    type: GAUGE
    attrNameSnakeCase: true
  - pattern: 'java.lang<type=MemoryPool,name=(?>.*)><>(usage|peak_usage)?: (?>.*)'
    name: $2_$3_bytes
    type: GAUGE
    attrNameSnakeCase: true
  - pattern: 'java.lang<type=GarbageCollector,name=(?>.*)><>collection_time(?:to_ms)?:'
    name: gc_$1_$2_time_ms
    type: GAUGE
    attrNameSnakeCase: true
  - pattern: 'java.lang<type=MemoryPool,name=(?>.*)><>usage_threshold:'
    name: memorypool_$1_usage_threshold_bytes
    type: GAUGE
    attrNameSnakeCase: true