template:
  domain: http://domain.com
  enable:
    cache: combination # guava:本地缓存,redis:redis缓存,combination:组合缓存
    lock: redisson # jvm:jvm锁,redisson:redisson分布式锁
    message-driven: rocketmq # springevent:spring事件,rabbitmq:RabbitMQ消息队列,rocketmq:RocketMQ消息队列
