eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 10 #服务刷新时间配置，每隔这个时间会主动心跳一次

spring:
  rabbitmq:
    addresses: 172.16.1.52:5672,172.16.1.52:5674
    username: lssq
    password: lssq@xxx1
    virtual-host: lssq
