server:
  port: 8001

spring:
  application:
    name: template-order
  profiles:
    active: dev

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true # 注册到Eureka Server，默认true
    fetch-registry: true # 从Eureka Server获取注册信息，默认true
    service-url: # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用,分隔
      defaultZone: http://127.0.0.1:7001/eureka/

#断路器
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE #隔离策略,默认THREAD
          thread:
            timeoutInMilliseconds: 60000