# =================== 路由配置文件 ===================
spring:
  cloud:
    gateway:
      default-filters:
        - name: ModifyResponseBody
          args:
            inClass: java.lang.String
            outClass: java.lang.String
            rewriteFunction: "#{@logResponseBody}"
      # 路由数组：指当请求满足什么样的断言时，转发到哪个服务上
      routes:
        # 路由标识，要求唯一，名称任意
        - id: gateway-template-auth
          # 请求最终被转发到的目标地址
          uri: lb://template-auth
          # 设置断言
          predicates:
            # Path Route Predicate Factory 断言，满足 /auth/** 路径的请求都会被路由到 lb://template-auth 这个uri中
            - Path=/auth/**
          # 配置过滤器（局部）
          filters:
            # StripPrefix：去除原始请求路径中的前1级路径，即/auth
            - StripPrefix=1
        - id: gateway-template-auth-/web/data
          uri: lb://template-auth
          predicates:
            - Path=/web/data
        - id: gateway-template-auth-/web/data2
          uri: lb://template-auth
          predicates:
            - Path=/web/data2
        - id: gateway-template-web
          uri: lb://template-web
          # 设置断言
          predicates:
            - Path=/web/**
          # 配置过滤器（局部）
          filters:
            # StripPrefix：去除原始请求路径中的前1级路径，即/web
            - StripPrefix=1
        - id: gateway-template-app
          uri: lb://template-app
          # 设置断言
          predicates:
            - Path=/app/**
          # 配置过滤器（局部）
          filters:
            # StripPrefix：去除原始请求路径中的前1级路径，即/app
            - StripPrefix=1