eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 10 #服务刷新时间配置，每隔这个时间会主动心跳一次

spring:
  profiles:
    include: routes,rabbitmq-dev,apollo-dev
    
template:
  domain: http://d-domain.com
  enable:
    redis: false
    rabbitmq: false

# Token 配置
token:
  # 密钥
  secret: hxqhjvtam5
