template:
  domain: http://d-domain.com
  message-driven: springevent # springevent:spring事件,rabbitmq:RabbitMQ消息队列,rocketmq:RocketMQ消息队列

# Token 配置
token:
  # 密钥
  secret: hxqhjvtam5

# 开发者路由配置
developer:
  enabled: true
  headers: x-deviceid,x-token
