# =================== 路由配置文件 ===================
spring:
  cloud:
    gateway:
      # 路由数组：指当请求满足什么样的断言时，转发到哪个服务上
      routes:
        # 路由标识，要求唯一，名称任意
        - id: gateway-template-web
          # 请求最终被转发到的目标地址
          uri: lb://template-web
          # 设置断言
          predicates:
            # Path Route Predicate Factory 断言，满足 /web/** 路径的请求都会被路由到 lb://template-web 这个uri中
            - Path=/web/**
          # 配置过滤器（局部）
          filters:
            # StripPrefix：去除原始请求路径中的前1级路径，即/web
            - StripPrefix=1
        - id: gateway-template-app
          uri: lb://template-app
          # 设置断言
          predicates:
            - Path=/app/**
          # 配置过滤器（局部）
          filters:
            # StripPrefix：去除原始请求路径中的前1级路径，即/app
            - StripPrefix=1
        - id: gateway-template-openapi
          uri: lb://template-openapi
          # 设置断言
          predicates:
            - Path=/openapi/**
          # 配置过滤器（局部）
          filters:
            # StripPrefix：去除原始请求路径中的前1级路径，即/openapi
            - StripPrefix=1
        - id: gateway-template-adminapi
          uri: lb://template-adminapi
          # 设置断言
          predicates:
            - Path=/adminapi/**
          # 配置过滤器（局部）
          filters:
            # StripPrefix：去除原始请求路径中的前1级路径，即/adminapi
            - StripPrefix=1
