# 下面是环境区分，多个配置以 ‘---’ 分开
---
# dev环境配置
spring:
  profiles: dev
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group # 默认的生产者组

---
# test环境配置
spring:
  profiles: test
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group # 默认的生产者组

---
# pre环境配置
spring:
  profiles: pre
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group # 默认的生产者组

---
# prod环境配置
spring:
  profiles: prod,prod-cn,prod-us
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: producer-group # 默认的生产者组
