server:
  port: 5001
  tomcat:
    min-spare-threads: 5
    max-threads: 100

spring:
  application:
    name: template-zuul
  profiles:
    active: dev

#为了避免日志目录生成{APP_NAME}_IS_UNDEFINED目录，不能使用默认配置logback.xml或logback-spring.xml命名，详细参考：http://www.itersblog.com/archives/5.html
logging:
  config: classpath:logback-conf.xml

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true # 注册到Eureka Server，默认true
    fetch-registry: true # 从Eureka Server获取注册信息，默认true
    service-url: # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用,分隔
      defaultZone: http://127.0.0.1:7001/eureka/
    
#网关转发也是使用ribbon来做负载的，网关超时时间>=内部服务超时时间（ReadTimeout）
ribbon:
  eager-load: #饥饿加载，默认false(用于防止第一次请求初始化耗时长而报错)
    enabled: true
    clients: template-auth,template-web,template-app #@FeignClient value值，多个逗号分隔
  #Ribbon重试次数(包含首次) = 1 + ribbon.MaxAutoRetries + ribbon.MaxAutoRetriesNextServer + (ribbon.MaxAutoRetries * ribbon.MaxAutoRetriesNextServer)
  MaxAutoRetries: 0 #同一实例最大重试次数，不包括首次调用。默认0
  MaxAutoRetriesNextServer: 1 #同一个微服务其他实例的最大重试次数，不包括第一次调用的实例。默认1
  OkToRetryOnAllOperations: false #是否所有操作（GET、POST等）都允许重试。默认false
  ServerListRefreshInterval: 2000 #从注册中心刷新服务器列表信息的时间间隔，默认2000ms
  #ConnectTimeout = feign.client.config.default.connectTimeout
  ConnectTimeout: 1000 #连接超时时间，默认无
  #ReadTimeout >= Ribbon重试次数(包含首次) * feign.client.config.default.connectTimeout
  ReadTimeout: 5000 #读取超时时间，默认无
  
zuul:
  # 前缀，可以用来做版本控制
  prefix: /api
  # 禁用默认路由，执行配置的路由
  ignored-services: "*"
  routes:
    # 配置4001认证中心微服务
    auth:
      serviceId: template-auth
      path: /auth/**
    # 配置6001接口微服务
    web:
      serviceId: template-web
      path: /web/**
    # 配置6002接口微服务
    app:
      serviceId: template-app
      path: /app/**

# Token 配置
token:
  # token名称
  name: x-token
  # token有效期，单位s 默认30天, -1代表永不过期 
  timeout: 2592000

# Sa-Token 配置
sa-token: 
  # token名称 (同时也是cookie名称)
  token-name: ${token.name}
  # token有效期，单位s 默认30天, -1代表永不过期 
  timeout: ${token.timeout}
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录) 
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token) 
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志 
  is-log: false
  # jwt秘钥 
  jwt-secret-key: ${token.secret}