# =================== 路由配置文件 ===================
zuul:
  # 前缀，可以用来做版本控制
  prefix: /
  # 禁用默认路由，执行配置的路由
  ignored-services: "*"
  routes:
    # 配置4001认证中心微服务
    auth:
      serviceId: template-auth
      path: /auth/**
    # 配置6001接口微服务
    web:
      serviceId: template-web
      path: /web/**
    # 配置6002接口微服务
    app:
      serviceId: template-app
      path: /app/**