eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 # Eureka注册中心（服务端）在收到客户端心跳之后，等待下一次心跳的超时时间，如果在这个时间内没有收到下次心跳，则移除该客户端。（默认90秒）
    lease-renewal-interval-in-seconds: 10 # 客户端向注册中心发送心跳的时间间隔（默认30秒）

spring:
  profiles:
    include: routes,rabbitmq-dev,apollo-dev
    
template:
  domain: http://d-domain.com
  enable:
    redis: false
    rabbitmq: false

# Token 配置
token:
  # 密钥
  secret: hxqhjvtam5
