spring:
  profiles:
    include: routes,eureka-pre,rabbitmq-pre,apollo-pre
    
template:
  domain: http://p-domain.com
  enable:
    rabbitmq: true

# Token 配置
token:
  # 密钥
  secret: hxqhjvtam5
