template:
  domain: http://d-domain.com
  enable:
    cache: guava # guava:本地缓存,redis:redis缓存,combination:组合缓存
    lock: jvm # jvm:jvm锁,redisson:redisson分布式锁
    idempotent: false
    message-queue: springevent # 选项：springevent,rabbitmq,rocketmq
  sqllimit:
    max: 9999

# 数据库表字段加密
encrypt:
  enable: false
  key: ftueqNbp5h5TIk5
  type: default
