template:
  domain: https://t-api-template.com
  enable:
    cache: redis # guava:本地缓存,redis:redis缓存,combination:组合缓存
    lock: redisson # jvm:jvm锁,redisson:redisson分布式锁
    idempotent: false
    message-queue: rocketmq # 选项：springevent,rabbitmq,rocketmq
  sqllimit:
    max: 9999

# 数据库表字段加密
encrypt:
  enable: false
  key: as3dyqNbp5h5Tgh5
  type: default
