spring:
  profiles:
    include: eureka-test,redis-test,rabbitmq-test
    
template:
  domain: http://t-domain.com
  enable:
    cache: guava # guava:本地缓存,redis:redis缓存,combination:组合缓存
    lock: redisson # jvm:jvm锁,redisson:redisson分布式锁
    idempotent: false
    rabbitmq: true
    data-encypt: false
    access-control: true

# Token 配置
token:
  # 密钥
  secret: hxqhjvtam5

# knife4j文档
knife4j:
  # 是否开启生产环境屏蔽   true:关闭swagger，false:开启swagger
  production: false
  basic:
    # 是否开启认证
    enable: false
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 123456
