template:
  domain: http://d-domain.com
  enable:
    cache: guava # guava:本地缓存,redis:redis缓存,combination:组合缓存
    lock: jvm # jvm:jvm锁,redisson:redisson分布式锁
    idempotent: false
    message-driven: springevent # springevent:spring事件,rabbitmq:RabbitMQ消息队列,rocketmq:RocketMQ消息队列
    data-encypt: false
    access-control: false

# Token 配置
token:
  # 密钥
  secret: hxqhjvtam5

# knife4j文档
knife4j:
  # 是否开启生产环境屏蔽   true:关闭swagger，false:开启swagger
  production: false
  basic:
    # 是否开启认证
    enable: false
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 123456
