spring:
  profiles:
    include: eureka-test,redis-test,rabbitmq-test
    
template:
  domain: http://t-domain.com
  enable:
    redis: true
    redisson: true
    idempotent: false
    rabbitmq: true
    data-encypt: false
  mock:
    time: true

# knife4j文档
knife4j:
  # 是否开启生产环境屏蔽   true:关闭swagger，false:开启swagger
  production: false
  basic:
    # 是否开启认证
    enable: false
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 123456
