eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 # Eureka注册中心（服务端）在收到客户端心跳之后，等待下一次心跳的超时时间，如果在这个时间内没有收到下次心跳，则移除该客户端。（默认90秒）
    lease-renewal-interval-in-seconds: 10 # 客户端向注册中心发送心跳的时间间隔（默认30秒）
  client:
    register-with-eureka: false # 注册到Eureka Server，默认true
    fetch-registry: false # 从Eureka Server获取注册信息，默认true

spring:
  profiles:
    include: redis-dev,rabbitmq-dev
    
template:
  domain: http://d-domain.com
  enable:
    redis: false
    redisson: false
    idempotent: false
    rabbitmq: false
    data-encypt: false
  mock:
    time: false

# knife4j文档
knife4j:
  # 是否开启生产环境屏蔽   true:关闭swagger，false:开启swagger
  production: false
  basic:
    # 是否开启认证
    enable: false
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 123456
