#建议在开发和测试环境下使用
eureka:
  server:
    enable-self-preservation: false # 默认情况下，eureka间隔60s将服务清单中没有续约的服务剔除（默认90s内没有续约），本地测试，关闭保护机制，直接让它实时剔除
    eviction-interval-timer-in-ms: 4000 #清理间隔（单位毫秒，默认是60*1000）