server:
  port: 7001

template:
  # eureka不同环境差异化配置
  eureka-server-enable-self-preservation: true
  eureka-server-eviction-interval-timer-in-ms: 60000
  eureka-client-register-with-eureka: true
  eureka-client-service-url-default-zone: http://127.0.0.1:7002/eureka/

logging:
  file:
    #日志文件目录。./表示相对于项目根目录，即项目根目录下的logs目录。也可配置绝对路径，如：/home/webapp/logs
    path: ./logs/${spring.application.name}-${server.port}
