spring:
  profiles:
    include: redis-prod,rabbitmq-prod
    
template:
  domain: http://domain.com
  enable:
    redis: true
    redisson: true
    idempotent: true
    rabbitmq: true
    data-encypt: true