eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 # Eureka注册中心（服务端）在收到客户端心跳之后，等待下一次心跳的超时时间，如果在这个时间内没有收到下次心跳，则移除该客户端。（默认90秒）
    lease-renewal-interval-in-seconds: 10 # 客户端向注册中心发送心跳的时间间隔（默认30秒）
  client:
    register-with-eureka: false # 注册到Eureka Server，默认true
    fetch-registry: false # 从Eureka Server获取注册信息，默认true

spring:
  profiles:
    include: redis-dev,rabbitmq-dev
    
template:
  domain: http://d-domain.com
  enable:
    redis: false
    redisson: false
    idempotent: false
    rabbitmq: false
    data-encypt: false
  mock:
    time: false
    oauthtool: true
    matool: true
    mptool: true

# Token 配置
token:
  # 密钥
  secret: hxqhjvtam5

wx:
  miniapp:
    configs:
      - appid: 1111 #微信小程序的appid
        secret: 1111 #微信小程序的Secret
        token: 1111 #微信小程序消息服务器配置的token
        aesKey: 1111 #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
  mp:
    configs:
      - appId: 1111 # 第一个公众号的appid
        secret: 1111 # 公众号的appsecret
        token: 111 # 接口配置里的Token值
        aesKey: 111 # 接口配置里的EncodingAESKey值
      - appId: 2222 # 第二个公众号的appid，以下同上
        secret: 1111
        token: 111
        aesKey: 111