# 熔断器 配置
spring:
  cloud:
    sentinel:
      enabled: true # 启用Sentinel
      eager: true # 启动马上初始化，默认false
      transport:
        dashboard: localhost:8080 # Sentinel控制台地址
        port: ${server.port}1 # 当前服务端口+1作为Sentinel本地监控端口，默认8719
#      datasource: # 数据记录到哪里？
#        ds1:
#          nacos:
#            server-addr: localhost:8848
#            dataId: ${spring.application.name}-sentinel
#            groupId: DEFAULT_GROUP
#            rule-type: flow
#            data-type: json
