# 下面是环境区分，多个配置以 ‘---’ 分开
---
# dev环境配置
spring:
  profiles: dev
  redis:
    host: 127.0.0.1 # 服务端地址
    port: 6379 # 服务端连接端口
    password: # 密码（默认为空）
    database: 0 # 数据库索引（默认为0）
    # redis已获取的连接，如果在N(毫秒)内连不上服务端，则放弃请求
    timeout: 1000 # 连接空闲超过N(毫秒)后关闭，0为禁用，这里配置值和redis.conf中tcp-keepalive值一致
    # 默认使用 lettuce 连接池
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数,默认8（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接,默认8
        min-idle: 0 # 连接池中的最小空闲连接 ,默认0
        max-wait: 5000 # 连接用完时，新的请求等待时间N(毫秒)，超过该时间抛出异常JedisConnectionException（默认-1，负值表示没有限制）

---
# test环境配置
spring:
  profiles: test
  redis:
    host: 127.0.0.1 # 服务端地址
    port: 6379 # 服务端连接端口
    password: # 密码（默认为空）
    database: 0 # 数据库索引（默认为0）
    # redis已获取的连接，如果在N(毫秒)内连不上服务端，则放弃请求
    timeout: 1000 # 连接空闲超过N(毫秒)后关闭，0为禁用，这里配置值和redis.conf中tcp-keepalive值一致
    # 默认使用 lettuce 连接池
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数,默认8（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接,默认8
        min-idle: 0 # 连接池中的最小空闲连接 ,默认0
        max-wait: 5000 # 连接用完时，新的请求等待时间N(毫秒)，超过该时间抛出异常JedisConnectionException（默认-1，负值表示没有限制）

---
# pre环境配置
spring:
  profiles: pre
  redis:
    host: 127.0.0.1 # 服务端地址
    port: 6379 # 服务端连接端口
    password: # 密码（默认为空）
    database: 0 # 数据库索引（默认为0）
    # redis已获取的连接，如果在N(毫秒)内连不上服务端，则放弃请求
    timeout: 1000 # 连接空闲超过N(毫秒)后关闭，0为禁用，这里配置值和redis.conf中tcp-keepalive值一致
    # 默认使用 lettuce 连接池
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数,默认8（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接,默认8
        min-idle: 0 # 连接池中的最小空闲连接 ,默认0
        max-wait: 5000 # 连接用完时，新的请求等待时间N(毫秒)，超过该时间抛出异常JedisConnectionException（默认-1，负值表示没有限制）

---
# prod环境配置
spring:
  profiles: prod,prod-cn,prod-us
  redis:
    host: 127.0.0.1 # 服务端地址
    port: 6379 # 服务端连接端口
    password: # 密码（默认为空）
    database: 0 # 数据库索引（默认为0）
    # redis已获取的连接，如果在N(毫秒)内连不上服务端，则放弃请求
    timeout: 1000 # 连接空闲超过N(毫秒)后关闭，0为禁用，这里配置值和redis.conf中tcp-keepalive值一致
    # 默认使用 lettuce 连接池
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数,默认8（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接,默认8
        min-idle: 0 # 连接池中的最小空闲连接 ,默认0
        max-wait: 5000 # 连接用完时，新的请求等待时间N(毫秒)，超过该时间抛出异常JedisConnectionException（默认-1，负值表示没有限制）
