app:
  # apollo的AppId，创建的时候建议使用spring.application.name一一对应创建，方便统一配置
  id: ${spring.application.name}
apollo:
  # 集群，一般不需要修改
  cluster: default
  bootstrap:
    # 开关，false表示不适用apollo
    enabled: true
    # 命名空间（多个使用英文逗号分隔）
    namespaces: application
  # apollo meta server地址（多个使用英文逗号分隔）
  meta: http://localhost:8080