spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 # 默认是0
    timeout: 5000 # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数,默认8（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接,默认8
        min-idle: 0 # 连接池中的最小空闲连接 ,默认0
        max-wait: 2000 # 连接池最大阻塞等待时间 ,默认-1（使用负值表示没有限制）