template:
  domain: http://t-domain.com
  enable:
    cache: guava # guava:本地缓存,redis:redis缓存,combination:组合缓存
    lock: redisson # jvm:jvm锁,redisson:redisson分布式锁
    idempotent: false
    message-driven: rocketmq # springevent:spring事件,rabbitmq:RabbitMQ消息队列,rocketmq:RocketMQ消息队列
  sqllimit:
    enable: true
    max: 9999
