template:
  domain: http://d-domain.com
  enable:
    cache: guava # guava:本地缓存,redis:redis缓存,combination:组合缓存
    lock: jvm # jvm:jvm锁,redisson:redisson分布式锁
    message-driven: springevent # springevent:spring事件,rabbitmq:RabbitMQ消息队列,rocketmq:RocketMQ消息队列
  sqllimit:
    enable: true
    max: 9999

filestorage:
  active: minio
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: pRYo5fCm9ZyVNKLA
    secretKey: Lv5yFUrBOXrNsZJVZ93XxSVl7JiNA99J
    bucketName: buket-template-test
    domain: http://127.0.0.1:9000/buket-template-test # 访问域名，例如：“https://image.t-domain.com”
