spring:
  config:
    import: classpath:bootstrap.yml # 在Spring Boot 2.7.x版本中，默认情况下，bootstrap.yml件不再被自动加载
  profiles:
    include: redis,rabbitmq,rocketmq,datasource
  main:
    allow-bean-definition-overriding: true
  resources:
    #用于告诉springboot应该在何处寻找静态资源，springboot默认的位置和优先级：spring.resources.static-locations=classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
    static-locations: /assets/
  mvc:
    #资源访问路径和spring.mvc.static-path-pattern匹配，当资源访问路径为"%/static/**”时，springboot才会处理请求
    static-path-pattern: /assets/**
    #相关页面解析器设置
    view:
      prefix: /views/
      suffix: .jsp

logging:
  #为了避免日志目录生成{APP_NAME}_IS_UNDEFINED目录，不能使用默认配置logback.xml或logback-spring.xml命名，详细参考：http://www.itersblog.com/archives/5.html
  config: classpath:logback-conf.xml
  file:
    #日志文件目录。./表示相对于项目根目录，即项目根目录下的logs目录。也可配置绝对路径，如：/home/webapp/logs
    path: ./logs/${spring.application.name}

mybatis-plus:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*.xml
  # 搜索指定包别名
  type-aliases-package: com.company.*.entity.*
  configuration:
    cacheEnabled: false # 使全局的映射器启用或禁用缓存
    lazyLoadingEnabled: true # 全局启用或禁用延迟加载。当禁用时，所有关联对象都会即时加载
    mapUnderscoreToCamelCase: true # 使用驼峰命名法转换字段
    jdbcTypeForNull: NULL # 设置但JDBC类型为空时,某些驱动程序要指定值,default:OTHER，插入空值时不需要指定类型
    logImpl: org.apache.ibatis.logging.log4j2.Log4j2Impl # 打印SQL语句
  global-config:
    db-config:
      #主键类型 0(AUTO):"数据库ID自增", 1(INPUT):"用户输入ID",2(ID_WORKER):"全局唯一ID (数字类型唯一ID)", 3(UUID):"全局唯一ID UUID";
      id-type: 0

template:
  threadpool:
    corePoolSize: 10
    maxPoolSize: 20
    queueCapacity: 200
    keepAliveSeconds: 60
    threadNamePrefix: t-subTask-
    waitForTasksToCompleteOnShutdown: true
    awaitTerminationSeconds: 60
  requestFilter:
    # 忽略日志打印匹配表达式，支持?匹配单个字符，*匹配多个字符
    ignoreLogPatterns: /assets/*,/favicon.ico
