-- 菜单
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}'		, '{module}_{modelName}'			, (select id from (SELECT id from sc_security_resource where `key` = '{module}') tt)						, '{module}'					, '0', NULL, NULL, '0', '{module.name.zh}-{module_name}', '1', '0', now(), now());
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}-首页'		, '{module}_{modelName}_index'		, (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}') tt)			, '{module}_{modelName}'		, '1', NULL, NULL, '0', '{module.name.zh}-{module_name}-首页', '1', '0', now(), now());
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}-首页-URL'	, '{module}_{modelName}_index_url'	, (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_index') tt)		, '{module}_{modelName}_index'	, '2', '/admin/{module}/{modelName}/index', 'get', '0', '获取{module_name}列表', '1', '0', now(), now());
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}-详情'		, '{module}_{modelName}_detail'		, (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}') tt)			, '{module}_{modelName}'		, '1', NULL, NULL, '0', '{module.name.zh}-{module_name}-详情', '1', '0', now(), now());
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}-详情-URL'	, '{module}_{modelName}_detail_url'	, (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_detail') tt)		, '{module}_{modelName}_detail'	, '2', '/admin/{module}/{modelName}/get', 'post', '0', '详情{module_name}', '1', '1', now(), now());
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}-新增'		, '{module}_{modelName}_create'		, (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}') tt)			, '{module}_{modelName}'		, '1', NULL, NULL, '0', '{module.name.zh}-{module_name}-新增', '1', '0', now(), now());
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}-新增-URL'	, '{module}_{modelName}_create_url'	, (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_create') tt)		, '{module}_{modelName}_create'	, '2', '/admin/{module}/{modelName}/save', 'post', '0', '新增{module_name}', '1', '1', now(), now());
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}-更新'		, '{module}_{modelName}_update'		, (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}') tt)			, '{module}_{modelName}'		, '1', NULL, NULL, '0', '{module.name.zh}-{module_name}-更新', '1', '0', now(), now());
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}-更新-URL'	, '{module}_{modelName}_update_url'	, (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_update') tt)		, '{module}_{modelName}_update'	, '2', '/admin/{module}/{modelName}/update', 'post', '0', '修改{module_name}', '1', '1', now(), now());
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}-删除'		, '{module}_{modelName}_delete'		, (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}') tt)			, '{module}_{modelName}'		, '1', NULL, NULL, '0', '{module.name.zh}-{module_name}-删除', '1', '0', now(), now());
INSERT INTO `sc_security_resource` (`id`, `name`, `key`, `pid`, `pkey`, `type`, `url`, `method`, `seq`, `desc`, `assign`, `log`, `create_time`, `update_time`) VALUES ('0', '{module.name.zh}-{module_name}-删除-URL'	, '{module}_{modelName}_delete_url'	, (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_delete') tt)		, '{module}_{modelName}_delete'	, '2', '/admin/{module}/{modelName}/remove', 'post', '0', '删除{module_name}', '1', '1', now(), now());


-- 菜单授权给admin角色
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}') tt));
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_index') tt));
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_index_url') tt));
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_detail') tt));
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_detail_url') tt));
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_create') tt));
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_create_url') tt));
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_update') tt));
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_update_url') tt));
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_delete') tt));
INSERT INTO `sc_security_role_res` (`role_id`, `resource_id`) VALUES ((select id from sc_security_role where superior =1), (select id from (SELECT id from sc_security_resource where `key` = '{module}_{modelName}_delete_url') tt));
