spring:
  profiles:
    include: redis-prod,rabbitmq-prod,elasticsearch-prod,apollo-prod

template:
  domain: http://domain.com
  enable:
    redis: true
    redisson: true
    idempotent: true
    rabbitmq: true
    data-encypt: true
  filestorage:
    active: local
    local:
      endpoint: /home/data/oss
      bucketName: buket-template
      domain: http://18.163.115.207:8011 # 访问域名，可以结合spring.resources.static-locations静态资源来使用 或 使用nginx配置访问目录指向
    minio:
      endpoint: http://127.0.0.1:9000
      accessKey: pRYo5fCm9ZyVNKLA
      secretKey: Lv5yFUrBOXrNsZJVZ93XxSVl7JiNA99J
      bucketName: buket-template
      domain: http://192.168.28.158:9000 # 访问域名，例如：“https://image.d-domain.com”

smssender:
  active: log
  # 打印日志（用于测试环境不想发送真实短信）
  log:
    signName: 测试
  # 阿里云短信
  ali:
    regionId: cn-hangzhou
    accessKey: LTAI5tRK8vFDnEijSRxNyDEs
    secretKey: ZIIW2Gt71FU8l48JyCIe4gzXmMYESe
    signName: XXX公司1
  # 腾讯短信
  tencent:
    appId: 1400006666
    regionId: ap-guangzhou
    accessKey: LTAIkcl1bVhsEpGf
    secretKey: D9hwgRigRI1Q6rIE4PBU1lmKsqTpUm
    signName: XXX公司2
