spring:
  profiles:
    include: redis-prod,rabbitmq-prod,elasticsearch-prod,apollo-prod

template:
  domain: http://domain.com
  enable:
    redis: true
    redisson: true
    idempotent: true
    rabbitmq: true
    data-encypt: true
  filestorage:
    active: minio
    minio:
      endpoint: http://127.0.0.1:9000
      accessKey: pRYo5fCm9ZyVNKLA
      secretKey: Lv5yFUrBOXrNsZJVZ93XxSVl7JiNA99J
      bucketName: buket-template
    alioss:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: LTAIkcl2bVhsEpGf
      secretAccessKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
      bucketName: buket-template
    tencentcos:
      endpoint: ap-guangzhou.myqcloud.com
      secretId: LTAIkcl2bVhsEpGf
      secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
      bucketName: buket-template
