spring:
  profiles:
    include: redis-prod,rabbitmq-prod,elasticsearch-prod,apollo-prod

template:
  domain: http://domain.com
  enable:
    redis: true
    redisson: true
    idempotent: true
    rabbitmq: true
    data-encypt: true
  filestorage:
    active: minio
    minio:
      endpoint: http://127.0.0.1:9000
      accessKey: pRYo5fCm9ZyVNKLA
      secretKey: Lv5yFUrBOXrNsZJVZ93XxSVl7JiNA99J
      bucketName: buket-template-dev
      domain: http://192.168.28.158:9000 # 访问域名，例如：“https://image.d-domain.com”
    alioss:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKey: LTAIkcl2bVhsEpGf
      secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
      bucketName: buket-template-dev
      domain: https://image.d-domain.com
    tencentcos:
      endpoint: ap-guangzhou.myqcloud.com
      accessKey: LTAIkcl2bVhsEpGf
      secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
      bucketName: buket-template-dev
      domain: # 访问域名，未配置域名会默认使用oss的url
    amazons3:
      endpoint: xxx.aws.com
      accessKey: LTAIkcl2bVhsEpGf
      secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
      bucketName: buket-template-dev
      domain: # 访问域名，未配置域名会默认使用oss的url
    baidubos:
      endpoint: xxx.baidu.com
      accessKey: LTAIkcl2bVhsEpGf
      secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
      bucketName: buket-template-dev
      domain: # 访问域名，未配置域名会默认使用oss的url
    huaweiobs:
      endpoint: xxx.huawei.com
      accessKey: LTAIkcl2bVhsEpGf
      secretKey: D9hwgRig2IKQ6rIE4PBUglmKsqTpUm
      bucketName: buket-template-dev
      domain: # 访问域名，未配置域名会默认使用oss的url
