eureka:
  instance:
    lease-expiration-duration-in-seconds: 30 #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-renewal-interval-in-seconds: 10 #服务刷新时间配置，每隔这个时间会主动心跳一次
  client:
    register-with-eureka: false # 注册到Eureka Server，默认true
    fetch-registry: false # 从Eureka Server获取注册信息，默认true

spring:
  profiles:
    include: redis-dev,rabbitmq-dev

template:
  domain: http://d-domain.com
  enable:
    redis: false
    redisson: false
    idempotent: false
    rabbitmq: false
    elasticsearch: false
    data-encypt: false
    access-control: false
  mock:
    time: false
