spring:
  profiles:
    include: redis
  main:
    allow-bean-definition-overriding: true

logging:
  #为了避免日志目录生成{APP_NAME}_IS_UNDEFINED目录，不能使用默认配置logback.xml或logback-spring.xml命名，详细参考：http://www.itersblog.com/archives/5.html
  config: classpath:logback-conf.xml
  file:
    #日志文件目录。./表示相对于项目根目录，即项目根目录下的logs目录。也可配置绝对路径，如：/home/webapp/logs
    path: ./logs/${spring.application.name}
    
# Feign 配置
feign:
  circuitbreaker:
    enabled: true  # 启用 Feign 熔断支持
    #httpclient: # 使用Apache HttpClient作为http客户端，默认HttpURLConnection
    #enabled: true
    #okhttp: # 使用okhttp作为http客户端  ，默认HttpURLConnection
    #enabled: true
  client:
    config:
      default:
        connectTimeout: 1000 # 连接超时时间，默认1000ms
        readTimeout: 5000 # 读取超时时间（单次请求），默认1000ms

# 熔断器 配置
resilience4j:
  timelimiter:
    configs:
      default:
        # 熔断器的超时时间 = Ribbon的重试次数(包含首次) * (ribbon.ReadTimeout + ribbon.ConnectTimeout)
        timeoutDuration: 5s  # 执行超时时间（整个调用过程>=单次请求*重试次数）
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        failureRateThreshold: 50    # 触发熔断的失败率阈值（%）
        minimumNumberOfCalls: 5     # 最小调用次数
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10       # 滑动窗口大小
        waitDurationInOpenState: 5s # 熔断开启后等待时间
        permittedNumberOfCallsInHalfOpenState: 3

template:
  sequence:
    datacenterId: 2
  threadpool:
    corePoolSize: 10
    maxPoolSize: 20
    queueCapacity: 200
    keepAliveSeconds: 60
    threadNamePrefix: t-subTask-
    waitForTasksToCompleteOnShutdown: true
    awaitTerminationSeconds: 60

# XXL-JOB配置，详细介绍请看XxlJobConfig
xxl:
  job:
    admin:
      # 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://127.0.0.1:8080/xxl-job-admin
    # 执行器通讯TOKEN [选填]：非空时启用；
    accessToken: default_token # 与xxl-job-admin的配置保持一致，如果要启用自动注册，必填
    executor:
      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
      appname: job-executor
      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address: 
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip: 
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
      port: 0
      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: ${logging.file.path}/jobhandler
      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30
