spring:
  config:
    import: classpath:bootstrap.yml # 在Spring Boot 2.7.x版本中，默认情况下，bootstrap.yml件不再被自动加载
  profiles:
    include: gracefulresponse,developer,threadpool,feign,resilience4j,sentinel,redis,rabbitmq,rocketmq,messagedriven,cachemanager,datasource,canal # 项目中增加配置application-*.yml可覆盖boot-starter-*的默认配置application-*.yml
  main:
    allow-bean-definition-overriding: true
  messages:
    # i18n国际化设置
    basename: i18n/messages,i18n-framework/messages # 默认名称，可以写多个,用逗号分隔
    encoding: UTF-8 # 国际化资源文件编码，默认UTF-8
    fallback-to-system-locale: true # 找不到对应区域的语言时，是否回退到系统区域的语言，默认 true
    always-use-message-format: false # 是否总是使用MessageFormat进行格式化，默认false
    use-code-as-default-message: true # 找不到code时,是否直接返回code值，而不是抛异常，默认false，抛异常
  mail:
    host: smtp.qq.com
    port: 465
    username: 888888888@qq.com # 发件人
    password: 111111111 # 发件人密码
    properties:
      mail.smtp.ssl.enable: false # 使用ssl连接
      mail.smtp.ssl.trust: '*' # 信任所有主机
  cloud:
    loadbalancer:
      eager-load: # spring-cloud-commons-3.1.8 没有eager-load，参考spring cloud高版本实现饥饿加载
        clients: template-user

template:
  sequence:
    datacenterId: 1
