spring:
  application:
    name: template-order2
    
template:
  domain: http://t-domain.com
  enable:
    redis: false
    redisson: false
    idempotent: false
    rabbitmq: false
    data-encypt: false
    access-control: false
    rabbitmq22: sdfdf