spring:
  profiles:
    include: eureka-pre,redis-pre,rabbitmq-pre
    
template:
  domain: http://p-domain.com
  enable:
    redis: true
    redisson: true
    idempotent: false
    rabbitmq: true
  sign:
    check: true
