template:
  domain: http://d-domain.com
  enable:
    cache: guava # guava:本地缓存,redis:redis缓存,combination:组合缓存
    lock: jvm # jvm:jvm锁,redisson:redisson分布式锁
    idempotent: false
    message-driven: springevent # springevent:spring事件,rabbitmq:RabbitMQ消息队列,rocketmq:RocketMQ消息队列

sign:
  check: false
  reqValidSeconds: 6000 # 请求有效秒数
  nonceValid: false # 校验nonce随机数，打开后重放请求不通过
  accounts:
    - appid: 13532515
      appsecret: b5d89c15161240d5ac17e846ab146721
    - appid: 33804682
      appsecret: 036bf98406d94349a3fb321ae72dbd12
    - appid: 56006206
      appsecret: 9cb7f98c222e4cf5aee85b63b254c1d9

# knife4j文档，访问地址：http://localhost:xxxx/doc.html
knife4j:
  enable: true # 增强模式开关
  production: false # 是否开启生产环境屏蔽   true:关闭swagger，false:开启swagger
  basic:
    enable: false  # 是否开启认证
    username: admin # Basic认证用户名
    password: 123456 # Basic认证密码
