spring:
  profiles:
    include: eureka-dev,redis-dev,rabbitmq-dev
    
template:
  domain: http://d-domain.com
  enable:
    cache: guava # guava:本地缓存,redis:redis缓存,combination:组合缓存
    redisson: false
    idempotent: false
    rabbitmq: false
  sign:
    check: false
