template:
  domain: http://p-domain.com
  enable:
    cache: guava # guava:本地缓存,redis:redis缓存,combination:组合缓存
    lock: redisson # jvm:jvm锁,redisson:redisson分布式锁
    idempotent: false
    message-queue: rocketmq # 选项：springevent,rabbitmq,rocketmq

sign:
  check: true
  reqValidSeconds: 60 # 请求有效秒数
  nonceValid: true # 校验nonce随机数，打开后重放请求不通过
  accounts:
    - appid: 13532515
      appsecret: b5d89c15161240d5ac17e846ab146721
    - appid: 33804682
      appsecret: 036bf98406d94349a3fb321ae72dbd12
    - appid: 56006206
      appsecret: 9cb7f98c222e4cf5aee85b63b254c1d9
