spring:
  profiles:
    include: eureka-pre,redis-pre,rabbitmq-pre
    
template:
  domain: http://p-domain.com
  enable:
    cache: guava # guava:本地缓存,redis:redis缓存,combination:组合缓存
    redisson: true
    idempotent: false
    rabbitmq: true
  sign:
    check: true
