spring:
  profiles:
    include: eureka-dev,redis-dev,rabbitmq-dev
    
template:
  domain: http://d-domain.com
  enable:
    redis: false
    redisson: false
    idempotent: false
    rabbitmq: false
  sign:
    check: false
